--- ! AWS Credentials File
aws_access_key:  <access-key>
aws_secret_key:  <secret-key>
!  1.  Create a master password file containing your master password in ~/ansible_vault.pwd
!  2.  Replace the two variables above with your access & secret keys.
!  3.  Save this file, then encrypt with ansible-vault.
!  4.  ansible-vault encrypt --vault-password-file=~/ansible_vault.pwd aws_credentials.yml
!  5.  Cat aws_credentials to ensure encryption
!
!  WARNING:  Be sure to encrypt this file with ansible-vault before checking into Github.
!            Never check files with credentials or other private information without first encrypting them.
!            Also, never check ansible_vault.pwd into your repo, EVER!