- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - name:  Create MariaDB
    rds:
      aws_access_key: "{{  aws_access_key  }}"
      aws_secret_key: "{{  aws_secret_key  }}"
      command: create
      instance_name: new-database
      db_engine: MySQL
      size: 5
      instance_type: db.t2.micro
      username: mysql_admin
      password: 1nsecure
      region: us-west-2
      tags:
        Environment: testing
        Application: cms