- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - name: Abort if ENV variable not set
    fail: msg="Required -e=[dev|prod], aborting - - -"
    when: ENV is not defined

  - name:  Include Vars
    include_vars: "{{  item  }}"
    with_fileglob:
      - "{{  ENV  }}_vars/all/*.yml"

  - name:  showvars
    debug: msg="showvar {{  aws_access_key  }}"

  - name: Abort if aws_access_key variable not set
    fail: msg="aws_access_key is missing, aborting - - -"
    when: aws_access_key is not defined

  - name: Abort if aws_secret_key variable not set
    fail: msg="aws_secret_key is missing, aborting - - -"
    when: aws_secret_key is not defined


  - name:  Create MariaDB
    rds:
      aws_access_key: "{{  aws_access_key  }}"
      aws_secret_key: "{{  aws_secret_key  }}"
      command: create
      instance_name: new-database
      db_engine: MySQL
      size: 5
      instance_type: db.t2.micro
      username: mysql_admin
      password: 1nsecure
      region: us-west-2
      tags:
        Environment: testing
        Application: cms